version: '3.8'

services:
  database:
    build:
      context: ./containers/database
      dockerfile: Dockerfile.dev
    ports:
      - "5432:5432"
    volumes:
      - ./dev-deployments/database/data:/var/lib/postgresql/data
      - ./dev-deployments:/deployments
    env_file:
      - .env.prod
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "/scripts/check_health.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  blockchain:
    build:
      context: ./containers/blockchain
      dockerfile: Dockerfile.dev
    ports:
      - "8545:8545"
    env_file:
      - .env.prod
    volumes:
      - ./dev-deployments:/app/deployments
    networks:
      - app-network
    restart: always
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "/scripts/check_health.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    build:
      context: ./containers/mailhog
      dockerfile: Dockerfile.dev
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - ./dev-deployments:/deployments
    networks:
      - app-network
    depends_on:
      - database
      - blockchain
    healthcheck:
      test: ["CMD", "/scripts/check_health.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./containers/backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./dev-deployments:/app/deployments
      - ./dev-deployments/backend/migrations:/app/prisma/migrations
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env.prod
    environment:
      - DATABASE_URL=postgresql://my_user:my_password@database:5432/my_database?schema=public
    depends_on:
      - database
      - mailhog
      - blockchain
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "/scripts/check_health.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./containers/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    env_file:
      - .env.prod
    volumes:
      - ./dev-deployments:/app/deployments
    networks:
      - app-network
    depends_on:
      - database
      - mailhog
      - blockchain
      - backend
    healthcheck:
      test: ["CMD", "/scripts/check_health.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
